### ISSUE TITLE
Set /LARGEADDRESSAWARE linker option (x86 only)

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp.BrowserSubProcess.NetCore#2]
X86 version needs to be large address aware.

**Comment by perlun** [comment]
What does "large address aware" mean in this context? (Just asking out of curiosity. :slightly_smiling_face:)

**Comment by amaitland** [comment]
To access more than 2gb of memory the x86 version needs to have the   /LARGEADDRESSAWARE linker option specified. 

https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=vs-2019

Also reminds me we should set tsaware for both x86 and x64 

https://docs.microsoft.com/en-us/cpp/build/reference/tsaware-create-terminal-server-aware-application?view=vs-2019
